/**
 * Custom Style Dictionary formats for Web (CSS custom properties + JSON).
 */

import type { Format, FormatFnArguments } from 'style-dictionary/types';

function kebabCase(path: string[]): string {
  return path.join('-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function camelCase(path: string[]): string {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

/**
 * css/colorVariables – CSS custom properties for primitive colors.
 */
export const cssColorVariables: Format = {
  name: 'css/colorVariables',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = kebabCase(token.path);
      const hex = (token.$value || token.value) as string;
      return `  --nucleus-${name}: ${hex};`;
    });

    return [
      '/* Generated by Nucleus – do not edit manually */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};


/**
 * json/flat – Flat JSON object for all tokens, used by the website.
 */
export const jsonFlat: Format = {
  name: 'json/flat',
  format: ({ dictionary }: FormatFnArguments) => {
    const result: Record<string, unknown> = {};

    for (const token of dictionary.allTokens) {
      const key = camelCase(token.path);
      const value = token.$value ?? token.value;
      result[key] = value;
    }

    return JSON.stringify(result, null, 2) + '\n';
  },
};
