/**
 * Custom Style Dictionary formats for Swift / SwiftUI output.
 *
 * All generated types are standalone – no dependency on platform Color or Font types.
 * Colors are raw hex strings; typography is a plain NucleusFontSpec struct.
 * The consuming app bridges these to its own platform types.
 */

import type { Format, FormatFnArguments } from 'style-dictionary/types';
import type { TypographyTokenValue } from './types.js';

function hexOnly(hex: string): string {
  return hex.replace('#', '').toUpperCase();
}

function camelCase(path: string[]): string {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

/**
 * swift/nucleusColorDefaults – Standalone NucleusColorPalette with String hex constants.
 */
export const swiftColorDefaults: Format = {
  name: 'swift/nucleusColorDefaults',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = camelCase(token.path);
      const hex = hexOnly((token.$value || token.value) as string);
      return `    public static let ${name} = "${hex}"`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by Nucleus – do not edit manually',
      'public enum NucleusColorPalette {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/nucleusColorTheme – Standalone NucleusLightColorTokens / NucleusDarkColorTokens with String hex constants.
 */
export const swiftColorTheme: Format = {
  name: 'swift/nucleusColorTheme',
  format: ({ dictionary, options }: FormatFnArguments) => {
    const structName = (options.structName as string) || 'NucleusLightColorTokens';
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'color' && t.path[0] === 'semantic',
    );

    const lines = tokens.map((token) => {
      const name = camelCase(token.path.slice(1));
      const hex = hexOnly((token.$value || token.value) as string);
      return `    public static let ${name} = "${hex}"`;
    });

    return [
      'import Foundation',
      '',
      `// Generated by Nucleus – do not edit manually`,
      `public enum ${structName} {`,
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/nucleusFontDefaults – Standalone NucleusTypography with NucleusFontSpec values.
 */
export const swiftFontDefaults: Format = {
  name: 'swift/nucleusFontDefaults',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'typography',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = (token.$value || token.value) as TypographyTokenValue;
      return `    public static let ${name} = NucleusFontSpec(size: ${v.fontSize}, weight: ${v.fontWeight}, letterSpacing: ${v.letterSpacing}, lineHeight: ${v.lineHeightMultiplier})`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by Nucleus – do not edit manually',
      'public struct NucleusFontSpec: Sendable {',
      '    public let size: Double',
      '    public let weight: Int',
      '    public let letterSpacing: Double',
      '    public let lineHeight: Double',
      '}',
      '',
      'public enum NucleusTypography {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/spacing – Spacing enum with CGFloat constants.
 */
export const swiftSpacing: Format = {
  name: 'swift/spacing',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'dimension' && t.path[0] === 'spacing',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = (token.$value ?? token.value) as number;
      return `    public static let ${name}: CGFloat = ${v}`;
    });

    return [
      'import CoreGraphics',
      '',
      '// Generated by Nucleus – do not edit manually',
      'public enum NucleusSpacing {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};
