/**
 * Custom Style Dictionary formats for Swift / SwiftUI output.
 *
 * All generated types are standalone – no dependency on platform Color types.
 * Colors are raw hex strings.
 * The consuming app bridges these to its own platform types.
 */

import type { Format, FormatFnArguments } from 'style-dictionary/types';

function hexOnly(hex: string): string {
  return hex.replace('#', '').toUpperCase();
}

function camelCase(path: string[]): string {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

/**
 * swift/nucleusColorDefaults – Standalone NucleusColorPalette with String hex constants.
 */
export const swiftColorDefaults: Format = {
  name: 'swift/nucleusColorDefaults',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = camelCase(token.path);
      const hex = hexOnly((token.$value || token.value) as string);
      return `    public static let ${name} = "${hex}"`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by Nucleus – do not edit manually',
      'public enum NucleusColorPalette {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

